import Head from "next/head";
import TopBanner from "../components/HomePage/TopBanner";
import MiddleBanner from "../components/HomePage/MiddleBanner";
import Service from "../components/HomePage/Service";
import ServiceDetails from "../components/HomePage/ServiceDetails";
import Reviews from "../components/Reviews/Reviews";
import React, { useContext } from "react";
import { AuthContext } from "../components/Contexts/AuthProvider";
import Lottie from "lottie-react";
import loader from "../public/data/Heart-2.json";

export default function Home() {
  const { loading } = React.useContext(AuthContext);
  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className=" w-[200px] h-[200px]">
          <Lottie animationData={loader} loop={true} />
        </div>
      </div>
    );
  }
  return (
    <div>
      <Head>
        <title>T- therapeutic touchpoint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopBanner />
        <Service />

        <ServiceDetails />
        <MiddleBanner />
        <Reviews />
      </main>
    </div>
  );
}
