import Head from 'next/head'
import TopBanner from '../components/HomePage/TopBanner'
import MiddleBanner from '../components/HomePage/MiddleBanner'
import Service from '../components/HomePage/Service'
import ServiceDetails from '../components/HomePage/ServiceDetails'
import Reviews from '../components/Reviews/Reviews'

export default function Home() {
  return (
    <div>
      <Head>
        <title>T- therapeutic touchpoint</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <TopBanner/>
      <MiddleBanner/>
      <Service/>
      <ServiceDetails/>
      <Reviews/>
    </main>
      
    </div>
  )
}
